export default {
    dbConnectionFailure: '資料庫連線失敗！',
    insertFailure: '新增失敗！',
    inputFormatError: '輸入格式有誤，請重新確認！',
    loginError: '帳號、密碼錯誤，請重新輸入！',
    passwordError: '密碼錯誤，請重新輸入！',
    loginRecordFailure: '登入記錄發生錯誤！',
    updateUserFailure: '帳號資料修改失敗！',
    invalidToken: '不合法的token！',
    forbidden: '無訪問權限！',
    noUser: '無此會員資料！',
    insertUserActionFailure: '記錄用戶行為發生錯誤！',
    getUserFailure: '取用戶資料發生錯誤！',
    getUsersFailure: '取所有用戶資料發生錯誤！',
    getDataFailure: '取資料發生錯誤！',
    emailVerifiedNotYet: '請先通過email驗證！',
    emailVerifiedError: '過email驗證發生錯誤！',
    refreshTokenFailure: 'refresh token失敗！',
    tokenNotExpiredYet: 'token尚未過期！',
    verifyingEmailSubject: 'AHA後端Email驗證',
    clickUrlBelow2Verify: '請點擊下方連結完成Email驗證',
    verifyingEmailLinkError: 'Email認證連結錯誤',
    passwordFormat: '密碼至少需要一個小寫字母、一個大小字母、一個數字、一個特殊符號以及長度超過八！'
};
